export const KEYS = {
    SECRET: 'SECRET',
    API_KEYS_MY_KEYS: 'API_KEYS_MY_KEYS',
    API_KEYS_PARTNER_KEYS: 'API_KEYS_PARTNER_KEYS',
    SELECTED_THEME: 'SELECTED_THEME',
    DATA_MIGRATION_VERSION: 'DATA_MIGRATION_VERSION',
    LANG: 'LANG',
} as const;
