import type { MyEnum } from "../../types/common";

export const PATHS: KeyEqualValue = getChannelPaths();

type KeyEqualValue = MyEnum<ReturnType<typeof getChannelPaths>>;

function getChannelPaths() {
  return Object.freeze({
    GET_ACCOUNTS: 'GET_ACCOUNTS',
    DELETE_ACCOUNTS: 'DELETE_ACCOUNTS',
    ADD_ACCOUNTS: 'ADD_ACCOUNTS',
    PUT_ACCOUNTS: 'PUT_ACCOUNTS',
    PUT_FRIENDS: 'PUT_FRIENDS',
    GET_FRIENDS: 'GET_FRIENDS',
    ADD_FRIENDS: 'ADD_FRIENDS',
    DELETE_FRIENDS: 'DELETE_FRIENDS',
    GET_FRIENDS_BY_ACCOUNT_ID: 'GET_FRIENDS_BY_ACCOUNT_ID',
    GET_FRIEND_BY_ID: 'GET_FRIEND_BY_ID',
    GET_PEER_ID_BY_ACC_ID_FOR_LIBP2P: 'GET_PEER_ID_BY_ACC_ID_FOR_LIBP2P',
    LOGIN: 'LOGIN',
    GET_ROOMS: 'GET_ROOMS',
    ADD_ROOMS: 'ADD_ROOMS',
    DELETE_ROOMS: 'DELETE_ROOMS',
    PUT_ROOMS: 'PUT_ROOMS',
    GET_ROOMS_BY_ACCOUNT_ID: 'GET_ROOMS_BY_ACCOUNT_ID',
    GET_ROOM_BY_ID: 'GET_ROOM_BY_ID',
  })
}
