version: '3.3'

services:
  lec-scripton:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        LES_CONTAINER_PORT: ${LES_CONTAINER_PORT}
    container_name: lec-scripton-development
    env_file:
      - .env
    environment:
      - LES_CONTAINER_PORT=${LES_CONTAINER_PORT}
    ports:
      # Проброс портов: "хост_порт:контейнер_порт"
      # LES_HOST_PORT - порт на хост машине (доступен извне)
      # LES_CONTAINER_PORT - внутренний порт контейнера (приложение слушает этот порт)
      - "${LES_HOST_PORT}:${LES_CONTAINER_PORT}"
    volumes:
      - ../:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh
