version: '3.8'

services:
  alpine-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpine-development
    volumes:
      - ../:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh
