services:
  les-scripton:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: les-scripton-development
    volumes:
      - ../:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh
